"""
TelNova Communications - Operations Analytics
Dashboard Data Export
=================================================
Reads the FINISHED workbook and embeds its contents directly into
dashboard/index.html as window.TELNOVA_OPS_DATA, plus inlines the
vendored Chart.js and SheetJS libraries -- a single, fully self-contained
HTML file with ZERO external network dependencies.

Field_Service_Orders (86k+ rows) is pre-aggregated (by month x order type
x region) since the dashboard only ever charts it in aggregate; the full
detail stays in the Excel workbook. Maintenance_Log is aggregated
similarly. Everything else is small enough to keep at full granularity.

Author: Milad Shabani
"""

import json
import re
import numpy as np
import pandas as pd
from datetime import datetime
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
VENDOR_DIR = os.path.join(SCRIPT_DIR, "vendor")

WORKBOOK_PATH = os.path.join(PROJECT_ROOT, "data", "Operations_Analytics_Workbook.xlsx")
DASHBOARD_HTML_PATH = os.path.join(PROJECT_ROOT, "dashboard", "index.html")
OUT_PATH = os.path.join(PROJECT_ROOT, "dashboard", "data.js")

HEADER_ROW_0INDEXED = {
    "Incident_Forecast": 4, "Demand_Forecast": 4, "Capacity_Exhaustion": 4, "Network_Risk": 4,
}


def read_sheet(sheet_name):
    header = HEADER_ROW_0INDEXED.get(sheet_name, 0)
    df = pd.read_excel(WORKBOOK_PATH, sheet_name=sheet_name, header=header, engine="openpyxl")
    df = df.dropna(how="all")
    return df


def to_records(df):
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = df[col].dt.strftime("%Y-%m-%d")
    df = df.replace({np.nan: None})
    return df.to_dict(orient="records")


def main():
    print("Reading workbook sheets...")
    uptime = read_sheet("Network_Uptime")
    incidents = read_sheet("Incidents")
    orders = read_sheet("Field_Service_Orders")
    callcenter = read_sheet("Call_Center_Ops")
    capacity = read_sheet("Network_Capacity")
    maintenance = read_sheet("Maintenance_Log")
    inventory = read_sheet("Inventory_CPE")
    incident_fc = read_sheet("Incident_Forecast")
    demand_fc = read_sheet("Demand_Forecast")
    capacity_fc = read_sheet("Capacity_Exhaustion")
    network_risk = read_sheet("Network_Risk")

    # ---- Pre-aggregate field service orders: by month x order type x region ----
    orders_agg = (orders.groupby(["Month", "OrderType", "Region"], as_index=False)
                  .agg(OrderCount=("OrderID", "count"),
                       AvgCycleTimeDays=("CycleTimeDays", "mean"))
                  )
    fix_rate = (orders.assign(Fixed=lambda d: (d["FirstTimeFix"] == "Yes").astype(int))
                .groupby(["Month", "OrderType", "Region"], as_index=False)["Fixed"].mean()
                .rename(columns={"Fixed": "FirstTimeFixRate"}))
    orders_agg = orders_agg.merge(fix_rate, on=["Month", "OrderType", "Region"])
    orders_agg["AvgCycleTimeDays"] = orders_agg["AvgCycleTimeDays"].round(2)
    orders_agg["FirstTimeFixRate"] = orders_agg["FirstTimeFixRate"].round(4)

    # ---- Pre-aggregate maintenance: by month x region x type ----
    maint_agg = (maintenance.groupby(["Month", "Region", "MaintenanceType"], as_index=False)
                 .agg(RecordCount=("MaintenanceID", "count"),
                      TotalHours=("DurationHours", "sum"),
                      TotalCostUSD=("CostUSD", "sum")))

    data = {
        "Uptime": to_records(uptime),
        "Incidents": to_records(incidents),
        "OrdersAgg": to_records(orders_agg),
        "CallCenter": to_records(callcenter),
        "Capacity": to_records(capacity),
        "MaintenanceAgg": to_records(maint_agg),
        "Inventory": to_records(inventory),
        "IncidentForecast": to_records(incident_fc),
        "DemandForecast": to_records(demand_fc),
        "CapacityExhaustion": to_records(capacity_fc),
        "NetworkRisk": to_records(network_risk),
        "_meta": {
            "generatedAt": datetime.now().isoformat(timespec="seconds"),
            "sourceWorkbook": "Operations_Analytics_Workbook.xlsx",
            "totalSubscribers": 1_047_500,
        },
    }

    for k, v in data.items():
        if isinstance(v, list):
            print(f"  {k:20s} -> {len(v)} records")

    js_content = (
        "// AUTO-GENERATED by scripts/export_dashboard_data.py -- do not edit by hand.\n"
        "// Build-time snapshot of Operations_Analytics_Workbook.xlsx so the dashboard works\n"
        "// offline with a plain double-click (no local server required).\n"
        "// Regenerate with: python scripts/build_all.py\n"
        "window.TELNOVA_OPS_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)
    size_kb = len(js_content.encode("utf-8")) / 1024
    print(f"\nWrote {OUT_PATH} ({size_kb:.0f} KB) [reference export, not required by the dashboard]")

    # ---- Embed data + vendor libs directly into dashboard/index.html ----
    with open(DASHBOARD_HTML_PATH, "r", encoding="utf-8") as f:
        html = f.read()

    inline_data_script = (
        '<script id="telnova-embedded-data">\n'
        "window.TELNOVA_OPS_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
        "</script>"
    )
    pattern = re.compile(r'<script id="telnova-embedded-data">.*?</script>', re.S)
    if not pattern.search(html):
        raise RuntimeError('Could not find the <script id="telnova-embedded-data"> placeholder in dashboard/index.html.')
    html = pattern.sub(lambda m: inline_data_script, html, count=1)

    def inline_vendor(html_text, placeholder_id, vendor_filename):
        vendor_path = os.path.join(VENDOR_DIR, vendor_filename)
        with open(vendor_path, "r", encoding="utf-8") as vf:
            lib_code = vf.read()
        pat = re.compile(r'<script id="' + re.escape(placeholder_id) + r'">.*?</script>', re.S)
        if not pat.search(html_text):
            raise RuntimeError(f'Could not find placeholder <script id="{placeholder_id}"> in dashboard/index.html.')
        replacement = f'<script id="{placeholder_id}">\n{lib_code}\n</script>'
        return pat.sub(lambda m: replacement, html_text, count=1)

    html = inline_vendor(html, "vendor-chartjs", "chart.umd.js")
    html = inline_vendor(html, "vendor-xlsx", "xlsx.full.min.js")

    with open(DASHBOARD_HTML_PATH, "w", encoding="utf-8") as f:
        f.write(html)

    html_size_kb = len(html.encode("utf-8")) / 1024
    print(f"Embedded dataset + Chart.js + SheetJS directly into {DASHBOARD_HTML_PATH} ({html_size_kb/1024:.2f} MB total)")
    print("This file now has ZERO external network dependencies -- it works fully offline.")


if __name__ == "__main__":
    main()
